---
- name: 'Anonymous'
  episodes:
  - number: '048'
    title: Lost in the Crowd
    url: https://docs.google.com/document/d/1073PT_ZCfFxWcDG-Jj-osZqZneYjFX3tSmiZ4ePHZ_0/edit
- name: snarp
  url: https://snarp.tumblr.com/
  episodes:
  - number: '043'
    title: Section 31
  - number: '044'
    title: Tightrope
  - number: '045'
    title: Blood Bag
  - number: '046'
    title: Literary Heights
  - number: '047'
    title: The New Door
  - number: '050'
    title: Foundations
  - number: '055'
    title: Pest Control
  - number: '059'
    title: Recluse
  - number: '061'
    title: Hard Shoulder
  - number: '062'
    title: First Edition
  - number: '063'
    title: The End of the Tunnel
  - number: '065'
    title: Binary
  - number: '067'
    title: Burning Desire
  - number: '106'
    title: A Matter Of Perspective
  - number: '107'
    title: Third Degree
  - number: '108'
    title: Monologue
  - number: '109'
    title: Nightfall
  - number: '110'
    title: Creature Feature
  - number: '116'
    title: The Show Must Go On
  - number: '117'
    title: Testament
  - number: '120'
    title: Eye Contact
  - number: '121'
    title: Far Away
  - number: '137'
    title: Nemesis
  - number: '148'
    title: Extended Surveillance
- name: 'tmatranscripts.tumblr.com'
  url: https://tmatranscripts.tumblr.com/
  episodes:
  - number: '118'
    title: The Masquerade
    url: https://tmatranscripts.tumblr.com/post/182633017311/mag118themasquerade-1pdf
  - number: '122'
    title: Zombie
    url: https://tmatranscripts.tumblr.com/post/183016022226/mag122zombie-1pdf
  - number: '123'
    title: Web Development
    url: https://tmatranscripts.tumblr.com/post/182772566591/mag123webdevelopmentpdf
  - number: '124'
    title: Left Hanging
    url: https://tmatranscripts.tumblr.com/post/182647387531/mag124lefthangingpdf
  - number: '124'
    title: Civilian Casualties
    url: https://tmatranscripts.tumblr.com/post/182621892246/mag125civiliancasualtiespdf
  - number: '126'
    title: Sculptor's Tool
    url: https://tmatranscripts.tumblr.com/post/182827165946/mag126sculptorstoolpdf
  - number: '127'
    title: Remains to be Seen
    url: https://tmatranscripts.tumblr.com/post/182968643421/mag127remainstobeseenpdf
  - number: '128'
    title: Heavy Goods
    url: https://tmatranscripts.tumblr.com/post/183121988991/mag128heavygoodspdf
  - number: '129'
    title: Submerged
    url: https://tmatranscripts.tumblr.com/post/183436679721/mag129submergedpdf
  - number: '130'
    title: Meat
    url: https://tmatranscripts.tumblr.com/post/183555648266/mag130meatpdf
  - number: '132'
    title: Entombed
    url: https://tmatranscripts.tumblr.com/post/183773620106/mag132entombedpdf
  - number: '133'
    title: Dead Horse
    url: https://tmatranscripts.tumblr.com/post/183964692121/mag133deadhorsepdf
  - number: '134'
    title: Time of Revelation
    url: https://tmatranscripts.tumblr.com/post/184109642408/mag134timeofrevelationpdf
  - number: '135'
    title: Dark Matter
    url: https://tmatranscripts.tumblr.com/post/184273160871/mag-135-dark-matter-case-0141407
  - number: '136'
    title: The Puppeteer
    url: https://tmatranscripts.tumblr.com/post/184630562096/mag136-the-puppeteer-case-0120112pdf
  - number: '138'
    title: The Architecture of Fear
    url: https://tmatranscripts.tumblr.com/post/184761985481/mag138-the-architecture-of-fear-case-8671302pdf
  - number: '139'
    title: Chosen
    url: https://tmatranscripts.tumblr.com/post/184922928921/mag139-chosen-case-0063011pdf
  - number: '140'
    title: The Movement of the Heavens
    url: https://tmatranscripts.tumblr.com/post/185087051726/mag140-the-movement-of-the-heavens-case
  - number: '142'
    title: Scrutiny
    url: https://tmatranscripts.tumblr.com/post/185891205991/mag142-scrutiny-case-0181206pdf
  - number: '143'
    title: Heart of Darkness
    url: https://tmatranscripts.tumblr.com/post/186049755301/mag143-heart-of-darkness-case-0181606pdf
  - number: '144'
    title: Decoded
    url: https://tmatranscripts.tumblr.com/post/186212766836/mag144-decrypted-case-0090310pdf
  - number: '145'
    title: Infectious Doubts
    url: https://tmatranscripts.tumblr.com/post/186389388926/mag145-infectious-doubts-case-0090202pdf
  - number: '146'
    title: Threshold
    url: https://tmatranscripts.tumblr.com/post/186567835611/mag146-threshold-case-0030109pdf
  - number: '147'
    title: Weaver
    url: https://tmatranscripts.tumblr.com/post/186721258601/mag147-weaver-case-0182007pdf
- name: 'YouTube Closed Captions (Auto-Generated)'
  episodes:
  - number: '051'
    title: High Pressure
    url: https://www.youtube.com/watch?v=BNIHaezwy-c
  - number: '052'
    title: Exceptional Risk
    url: https://www.youtube.com/watch?v=u-outt8lowg
  - number: '053'
    title: Crusader
    url: https://www.youtube.com/watch?v=bzZphRkToEs
  - number: '054'
    title: Still Life
    url: https://www.youtube.com/watch?v=1EHJ0UPaw9I
  - number: '056'
    title: Children of the Night
    url: https://www.youtube.com/watch?v=4sSoy43fQak
  - number: '057'
    title: Personal Space
    url: https://www.youtube.com/watch?v=2iPFjWmt1V8
  - number: '058'
    title: Trail Rations
    url: https://www.youtube.com/watch?v=d3rWiOsZeaI
  - number: '064'
    title: Burial Rites
    url: https://www.youtube.com/watch?v=bt81yVfaRmA
  - number: '066'
    title: Held In Customs
    url: https://www.youtube.com/watch?v=A84DqGwgPJM
  - number: '119'
    title: Stranger And Stranger
    url: https://www.youtube.com/watch?v=FYA_7TV_65w