---
- name: 'Anonymous'
  episodes:
  - number: '048'
    title: Lost in the Crowd
    url: https://docs.google.com/document/d/1073PT_ZCfFxWcDG-Jj-osZqZneYjFX3tSmiZ4ePHZ_0/edit
- name: prentissed
  url: http://prentissed.tumblr.com/
  episodes: 
  - number: '049'
    title: "The Butcher's Window"
    url: "https://docs.google.com/document/d/1O1SyQLTWyxAAoFgybv1thRzao2-gek4uevmHixWWPZg/edit?usp=sharing"
  - number: '051'
    title: "High Pressure"
    url: "https://docs.google.com/document/d/1nSof6i0l70dJbgOti3Oo_2HyvC_JrWYF-EkUsSo8C6Q/edit#"
  - number: '052'
    title: "Exceptional Risk"
    url: "https://docs.google.com/document/d/1AZAjU9X8aT2saX5zA8jSNlt0-0_3dLBvV6kPurvyj9g/edit?usp=sharing"
  - number: '053'
    title: "Crusader"
    url: "https://docs.google.com/document/d/1l10aGYpdS8N4nQ2JgKy-1XaKEGltpKXqZND22xLH55s/edit?usp=sharing"
  - number: '054'
    title: "Still Life"
    url: "https://docs.google.com/document/d/1sA6TNwrEUuVkVmfTw_ijqC1jE0nipxXxfPWAflxK0Ow/edit?usp=sharing"
  - number: '056'
    title: "Children of the Night"
    url: "https://docs.google.com/document/d/14HfarGxiz_W94C7gxzDHO7a2m1aSGshySUhZzR2VVo4/edit?usp=sharing"
  - number: '057'
    title: "Personal Space"
    url: https://docs.google.com/document/d/1hT2ceVz5QIKcCKSe6HBczgpma6U2upsaLhrTPutNsis/edit?usp=sharing
  - number: '058'
    title:  "Trail Rations"
    url: "https://docs.google.com/document/d/12jLUawePqnKBCUzz6lYEBVqYt-Og-DxbrkaSgxaGUZw/edit?usp=sharing"
  - number: '060'
    title: "The Observer Effect"
    url: "https://docs.google.com/document/d/1cM95nT_61C0_c_0YdO-4icwfR5jZ7QqEWEHBthJKTqM/edit?usp=sharing"
  - number: '064'
    title: "Burial Rites"
    url: "https://docs.google.com/document/d/1AVsSvuKX94PWkJJ6GQ7r-3wuAnlz06WrdsTioz7dB8w/edit?usp=sharing"
  - number: '066'
    title: "Held in Customs"
    url: "https://docs.google.com/document/d/17liqmFnVkHG85cfpaxxQfm2E_xHi-Hl4Ryo28SF4aSw/edit?usp=sharing"
  - number: '119'
    title: "Stranger And Stranger"
    url: "https://docs.google.com/document/d/1a2SWu5RmIE9D2ugIhHHHglfGiLFyKAjgO6C8MPb2hug/edit?usp=sharing"
  - number: '149'
    title: "Concrete Jungle"
    url: "https://docs.google.com/document/d/1Lf_yzIzAc0hBJ_gPqBF7PWtn3AoxHUJbzYsy3O_LcOU/edit"
  - number: '150'
    title: "Cul-de-Sac"
    url: "https://docs.google.com/document/d/1vSdhk343TtD5SVXTIMSJzRPV1Ns4QQGVTYhkU92-XGs/edit"
  - number: '151'
    title: "Big Picture"
    url: "https://docs.google.com/document/d/1gUPfDZtouJEokDAB1onP0VE6JilgDYRejfJeKO1RYL0/edit"
  - number: '152'
    title: "A Gravedigger's Envy"
    url: "https://docs.google.com/document/d/1Xy3N4aDj8BxCnDHgubhYNQF4NLoNdi_xxw6YnU4sVOg/edit"
  - number: '153'
    title: "Love Bombing"
    url: "https://docs.google.com/document/d/1KS4pNW69L392h_CBOXfKAo4XIVt1NRjqilBcRUKPUaY/edit"
  - number: '155'
    title: "Cost of Living"
    url: "https://docs.google.com/document/d/1YJy1myMK-n4nMRK1yVb3cv5fdG-NvO4WzJmCp_D5HxE/edit"
- name: snarp
  url: https://snarp.tumblr.com/
  episodes:
  - number: '043'
    title: "Section 31"
  - number: '044'
    title: "Tightrope"
  - number: '045'
    title: "Blood Bag"
  - number: '046'
    title: "Literary Heights"
  - number: '047'
    title: "The New Door"
  - number: '050'
    title: "Foundations"
  - number: '055'
    title: "Pest Control"
  - number: '059'
    title: "Recluse"
  - number: '061'
    title: "Hard Shoulder"
  - number: '062'
    title: "First Edition"
  - number: '063'
    title: "The End of the Tunnel"
  - number: '065'
    title: "Binary"
  - number: '067'
    title: "Burning Desire"
  - number: '106'
    title: "A Matter Of Perspective"
  - number: '107'
    title: "Third Degree"
  - number: '108'
    title: "Monologue"
  - number: '109'
    title: "Nightfall"
  - number: '110'
    title: "Creature Feature"
  - number: '116'
    title: "The Show Must Go On"
  - number: '117'
    title: "Testament"
  - number: '120'
    title: "Eye Contact"
  - number: '121'
    title: "Far Away"
  - number: '137'
    title: "Nemesis"
  - number: '148'
    title: "Extended Surveillance"
- name: 'tmatranscripts.tumblr.com'
  url: https://tmatranscripts.tumblr.com/
  episodes:
  - number: '118'
    title: "The Masquerade"
    url: "https://tmatranscripts.tumblr.com/post/182633017311/mag118themasquerade-1pdf"
  - number: '122'
    title: "Zombie"
    url: "https://tmatranscripts.tumblr.com/post/183016022226/mag122zombie-1pdf"
  - number: '123'
    title: "Web Development"
    url: "https://tmatranscripts.tumblr.com/post/182772566591/mag123webdevelopmentpdf"
  - number: '124'
    title: "Left Hanging"
    url: "https://tmatranscripts.tumblr.com/post/182647387531/mag124lefthangingpdf"
  - number: '124'
    title: "Civilian Casualties"
    url: "https://tmatranscripts.tumblr.com/post/182621892246/mag125civiliancasualtiespdf"
  - number: '126'
    title: "Sculptor's Tool"
    url: "https://tmatranscripts.tumblr.com/post/182827165946/mag126sculptorstoolpdf"
  - number: '127'
    title: "Remains to be Seen"
    url: "https://tmatranscripts.tumblr.com/post/182968643421/mag127remainstobeseenpdf"
  - number: '128'
    title: "Heavy Goods"
    url: "https://tmatranscripts.tumblr.com/post/183121988991/mag128heavygoodspdf"
  - number: '129'
    title: "Submerged"
    url: "https://tmatranscripts.tumblr.com/post/183436679721/mag129submergedpdf"
  - number: '130'
    title: "Meat"
    url: "https://tmatranscripts.tumblr.com/post/183555648266/mag130meatpdf"
  - number: '132'
    title: "Entombed"
    url: "https://tmatranscripts.tumblr.com/post/183773620106/mag132entombedpdf"
  - number: '133'
    title: "Dead Horse"
    url: "https://tmatranscripts.tumblr.com/post/183964692121/mag133deadhorsepdf"
  - number: '134'
    title: "Time of Revelation"
    url: "https://tmatranscripts.tumblr.com/post/184109642408/mag134timeofrevelationpdf"
  - number: '135'
    title: "Dark Matter"
    url: "https://tmatranscripts.tumblr.com/post/184273160871/mag-135-dark-matter-case-0141407"
  - number: '136'
    title: "The Puppeteer"
    url: "https://tmatranscripts.tumblr.com/post/184630562096/mag136-the-puppeteer-case-0120112pdf"
  - number: '138'
    title: "The Architecture of Fear"
    url: "https://tmatranscripts.tumblr.com/post/184761985481/mag138-the-architecture-of-fear-case-8671302pdf"
  - number: '139'
    title: "Chosen"
    url: "https://tmatranscripts.tumblr.com/post/184922928921/mag139-chosen-case-0063011pdf"
  - number: '140'
    title: "The Movement of the Heavens"
    url: "https://tmatranscripts.tumblr.com/post/185087051726/mag140-the-movement-of-the-heavens-case"
  - number: '142'
    title: "Scrutiny"
    url: "https://tmatranscripts.tumblr.com/post/185891205991/mag142-scrutiny-case-0181206pdf"
  - number: '143'
    title: "Heart of Darkness"
    url: "https://tmatranscripts.tumblr.com/post/186049755301/mag143-heart-of-darkness-case-0181606pdf"
  - number: '144'
    title: "Decoded"
    url: "https://tmatranscripts.tumblr.com/post/186212766836/mag144-decrypted-case-0090310pdf"
  - number: '145'
    title: "Infectious Doubts"
    url: "https://tmatranscripts.tumblr.com/post/186389388926/mag145-infectious-doubts-case-0090202pdf"
  - number: '146'
    title: "Threshold"
    url: "https://tmatranscripts.tumblr.com/post/186567835611/mag146-threshold-case-0030109pdf"
  - number: '147'
    title: "Weaver"
    url: "https://tmatranscripts.tumblr.com/post/186721258601/mag147-weaver-case-0182007pdf"
  - number: '154'
    title: "Bloody Mary"
    url: "https://tmatranscripts.tumblr.com/post/187820008016/mag154-bloody-mary-case-0082107pdf"